// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpendingTrack.Models;

namespace SpendingTrack.Migrations
{
    [DbContext(typeof(SpendingTrackContext))]
    [Migration("20181119064610_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("SpendingTrack.Models.SpendingItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<int>("Cost");

                    b.Property<string>("Currency");

                    b.Property<string>("Heading");

                    b.Property<string>("Note");

                    b.Property<int>("TripID");

                    b.HasKey("ID");

                    b.ToTable("SpendingItem");
                });
#pragma warning restore 612, 618
        }
    }
}
